bookstore/config/routes.rb
Bookstore::Application.routes.draw do

root :to => "users#index"

  resources :users do
	  member do
		get "add_book"
	  end
  end

  resources :user_books 

  resources :books
  

end

bookstore/app/models/book.rb
class Book < ActiveRecord::Base
	has_many :user_books
	has_many :users, :through => :user_books
	
	#book tiene muchos user_books
	#y ademas tiene muchos usuarios a traves de user_books
end

bookstore/app/models/user.rb
class User < ActiveRecord::Base
	has_many :user_books
	has_many :books, :through => :user_books
	
	#user tiene muchos user_books
	#y ademas tiene muchos libros a traves de user_books
end

bookstore/app/models/user_book.rb
class UserBook < ActiveRecord::Base
	belongs_to :user
	belongs_to :book
end

bookstore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

bookstore/app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

bookstore/app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController
end

bookstore/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  
  
  # Definimos add_book
  def add_book
	@user = User.find(params[:id])
  end
  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
	  format.xml  { render xml: @users }  #Asignando formato xml
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }	  
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

bookstore/app/helpers/application_helper.rb
module ApplicationHelper
end

bookstore/app/helpers/books_helper.rb
module BooksHelper
end

bookstore/app/helpers/user_books_helper.rb
module UserBooksHelper
end

bookstore/app/helpers/users_helper.rb
module UsersHelper
end

bookstore/app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bookstore/app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

bookstore/app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

bookstore/app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

bookstore/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

bookstore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
#Significa queva a tomar todas las paginas y las va a imprimir.
#yield incluye todas las paginas html aqui, es como si esta clase vendria ha ser la superclase.
# Esta carpeta layout es como la plantilla,siempre se va a buscar primero aqui

</body>
</html>

bookstore/app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>

	<%= f.error_notification %>
  
  <div class="inputs">
	<%= f.input :name %>
  </div>  
  
  <% #esto es un comentario %>
  
  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

bookstore/app/views/users/add_book.html.erb
<h2>Bienvenido, <%= @user.name %></h2>

<%= simple_form_for(@user) do |f| %>
	<%= f.association :books, :as => "check_boxes" %>
	<br />
	<%= f.button :submit %>
	
	
<% end %>




	
	
	

bookstore/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

bookstore/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

bookstore/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

bookstore/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<table>
	<% @user.books.each do |book| %>
		<tr>
			<td><%= book.title %></td>
		</tr>	
	<% end %>
</table>



<%# 
add_book: Agrega libro.
user: Es donde se encuentra la pantalla.
path: Con esto toma la ruta.
@user: Se envia como parametro el usuario.
%>

<%= link_to 'Add Book', add_book_user_path(@user) %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>