xmas_gift/config/routes.rb
XmasGift::Application.routes.draw do
  resources :gifts

  resources :people

end

xmas_gift/app/models/gift.rb
class Gift < ActiveRecord::Base
  belongs_to :person
end

xmas_gift/app/models/person.rb
class Person < ActiveRecord::Base
  has_many:gifts
end

xmas_gift/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

xmas_gift/app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gifts }
    end
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
    @gift = Gift.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gift }
    end
  end

  # GET /gifts/new
  # GET /gifts/new.json
  def new
    @gift = Gift.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gift }
    end
  end

  # GET /gifts/1/edit
  def edit
    @gift = Gift.find(params[:id])
  end

  # POST /gifts
  # POST /gifts.json
  def create
    @gift = Gift.new(params[:gift])

    respond_to do |format|
      if @gift.save
        format.html { redirect_to @gift, notice: 'Gift was successfully created.' }
        format.json { render json: @gift, status: :created, location: @gift }
      else
        format.html { render action: "new" }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gifts/1
  # PUT /gifts/1.json
  def update
    @gift = Gift.find(params[:id])

    respond_to do |format|
      if @gift.update_attributes(params[:gift])
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift = Gift.find(params[:id])
    @gift.destroy

    respond_to do |format|
      format.html { redirect_to gifts_url }
      format.json { head :no_content }
    end
  end
end

xmas_gift/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

xmas_gift/app/helpers/application_helper.rb
module ApplicationHelper
end

xmas_gift/app/helpers/gifts_helper.rb
module GiftsHelper
end

xmas_gift/app/helpers/people_helper.rb
module PeopleHelper
end

xmas_gift/app/views/gifts/_form.html.erb
<%= form_for(@gift) do |f| %>
  <% if @gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% @gift.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :person %><br />    
	<%= f.collection_select :person_id, Person.all, :id, :name, :prompt => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

xmas_gift/app/views/gifts/edit.html.erb
<h1>Editing gift</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

xmas_gift/app/views/gifts/index.html.erb
<h1>Listing gifts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Person</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @gifts.each do |gift| %>
  <tr>
    <td><%= gift.name %></td>
    <td><%= gift.person.name %></td>
    <td><%= link_to 'Show', gift %></td>
    <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
    <td><%= link_to 'Destroy', gift, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gift', new_gift_path %>

xmas_gift/app/views/gifts/new.html.erb
<h1>New gift</h1>

<%= render 'form' %>

<%= link_to 'Back', gifts_path %>

xmas_gift/app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @gift.name %>
</p>

<p>
  <b>Person:</b>
  <%= @gift.name %>
</p>


<%= link_to 'Edit', edit_gift_path(@gift) %> |
<%= link_to 'Back', gifts_path %>

xmas_gift/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>XmasGift</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

xmas_gift/app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

xmas_gift/app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

xmas_gift/app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

xmas_gift/app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

xmas_gift/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<ul>
  <% @person.gifts.each do |gift| %>
  <li><%= gift.name %></li>
  <%end%>
</ul>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>